### PR TITLE
Add FreeIPA support as a new LDAP vendor

### PR DESCRIPTION
**Pull request by edvalley**
@jrivard : This is the first approach for issue https://github.com/ldapchai/ldapchai/issues/26
Waiting for review...
Thanks

### CODE REVIEW

**Comment by jrivard** [comment]
So I think this is along the right lines, but the one concern I have is the directory detection in FreeIPAVendorFactory#detectVendorFromRootDSEData.  This seems to overlap with the same detection keys in DirectoryServer389#detectVendorFromRootDSEData.  This detection code is critical path for ldapchai (and PWM) to apply correct implementation.  This code should not depend on the order of the DirectoryVendor enum for correctness.   If there isn't enough difference to do the detection properly then thats probably a sign we should combine them.

**Comment by edvalley** [comment]
@jrivard : Oh, I see, you don't want the code to depend on the order. I think we could check for (only?) other attribute names specific to FreeIPA as detection keys, like `ipaDomainLevel`, `ipatopologyismanaged` (they don't have specific values we can check for), or `ipatopologypluginversion` (which value is now `1.0`, but obviously will change someday). So, do you think that logic will be enough to keep this implementation? Or, do you think we better combine FreeIPA and 389 Directory Server implementations? Personally, I think keeping them separate will help to have a cleaner and maintainable code. FreeIPA uses kerberos for all it's authentication stuff, so I think there's no much we can grab from 389 DS implementation around this. I'm planning to implement reading password policy, which will be necessary to check if a user is locked because of trying the wrong password too many times.
Again, thanks for your time.

**Comment by jrivard** [comment]
@edvalley  I'm not sure how the vendor checking should work because I'm not familiar enough with 389DS or FreeIPA.  I've been looking at the FreeIPA (https://www.freeipa.org/page/Demo) which is super helpful but I'm still pretty new to both.  In the meantime I'll rely on your judgement.

As far as the separate vs combined, if it was combined it might be more abstractly correct, but then we would need something like a feature flag to differentiate logic and each method would have to do checking, so it's probably more practical to keep them separate as long as the detection logic is reliable....

**Comment by jrivard** [comment]
@edvalley I'm planning a release soon, will you be able to work on this in the near future?

**Comment by edvalley** [comment]
Sorry, I've been busy. I'll find some spare time to work on it over this weekend.

**Comment by edvalley** [comment]
@jrivard I think it's ready. I'll wait for your review. Next commits will be about reading password policy. Thanks.

**Comment by edvalley** [comment]
@jrivard Sorry, I know this is maybe out of context and PWM related but, Is there a way we can use LDAP as the only password policy source? I always get the error about "Too many non-letter characters". Lightly reading PWM code, I think it's maybe merging LDAP policy with a default policy (I can be wrong). Do you think there is something that can be changed in order to get this to work?

**Comment by jrivard** [comment]
@edvalley so sorry this has taken forever.  I got distracted and missed your updates :(

Code looks good, thanks for your efforts, merging as is.

**Comment by jrivard** [comment]
> @jrivard Sorry, I know this is maybe out of context and PWM related but, Is there a way we can use LDAP as the only password policy source? I always get the error about "Too many non-letter characters". Lightly reading PWM code, I think it's maybe merging LDAP policy with a default policy (I can be wrong). Do you think there is something that can be changed in order to get this to work?

In PWM there is a setting to control if password policy comes from LDAP, PWM policy or is merged.  Merged is the default.

**Pull request merged**
